name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Iniciar sesión en Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - name: Crear Resource Groups
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --location eastus2 \
            --template-file infra/rg.bicep \
            --parameters infra/parameters/dev.rg.parameters.json

    - name: Desplegar recursos a los RG
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --location eastus2 \
            --template-file infra/subscription-PR.bicep \
            --parameters infra/parameters/pr.resources.parameters.json
