name: Deploy Visualizador - QA

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: qa
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Iniciar sesión en Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: false
    
    - name: Crear Resource Groups
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --location centralus \
            --template-file infra/rg.bicep \
            --parameters infra/parameters/dev.rg.parameters.json

    - name: Desplegar recursos a los RG
      uses: azure/cli@v1
      with:
        inlineScript: |
          az deployment sub create \
            --location centralus \
            --template-file infra/subscription-QA.bicep \
            --parameters infra/parameters/dev.resources.parameters.json

    - name: Azure Logout
      run: az logout
